[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[lint]
lint_on_build = false
exclude_lints = ["screaming-snake-case-immutable", "mixed-case-variable"]

[fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
